
set(TOOLCHAIN_PATH "C:/Keil_v5/ARM/ARMCLANG/bin")

# 设置交叉编译目标系统
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-m3)
set(CMAKE_SYSTEM_ARCH armv7-m)

set(CMAKE_C_COMPILER 			"${TOOLCHAIN_PATH}/armclang.exe")
set(CMAKE_CXX_COMPILER 			"${TOOLCHAIN_PATH}/armclang.exe")
set(CMAKE_ASM_COMPILER 			"${TOOLCHAIN_PATH}/armasm.exe")
set(CMAKE_C_LINK_EXECUTABLE 	"${TOOLCHAIN_PATH}/armlink.exe")
set(CMAKE_CXX_LINK_EXECUTABLE 	"${TOOLCHAIN_PATH}/armlink.exe")
set(CMAKE_ASM_LINK_EXECUTABLE 	"${TOOLCHAIN_PATH}/armlink.exe")

set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_CXX_COMPILER_WORKS TRUE)
set(CMAKE_ASM_COMPILER_WORKS TRUE)
